=begin
#API title

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::V1Api
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'V1Api' do
  before do
    # run before each test
    @instance = SwaggerClient::V1Api.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of V1Api' do
    it 'should create an instance of V1Api' do
      expect(@instance).to be_instance_of(SwaggerClient::V1Api)
    end
  end

  # unit tests for delete_v1_carts_favorite
  # Remove from Favorites
  # @param variant_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_v1_carts_favorite test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_v1_customer_addresses_id
  # address delete
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_v1_customer_addresses_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_v1_customers_credit_cards_card_id
  # remove credit cards
  # @param card_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_v1_customers_credit_cards_card_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_app_version
  # Show Min App version
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_app_version test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_carts
  # Get Cart
  # @param [Hash] opts the optional parameters
  # @option opts [String] :token 
  # @option opts [Integer] :use_birth_gift 
  # @option opts [Integer] :use_rebate_points 
  # @return [nil]
  describe 'get_v1_carts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_carts_favorites
  # get Favorites
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_carts_favorites test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_categories
  # Category Index
  # @param brand_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_categories test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_categories_id
  # Category Show
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_categories_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_collections
  # Collection Index
  # @param brand_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_collections test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_collections_id
  # Collection Show
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_collections_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_customer_addresses
  # address index
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_customer_addresses test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_customer_addresses_id
  # address show
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_customer_addresses_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_customers_credit_cards
  # get credit cards
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_customers_credit_cards test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_customers_credit_cards_get_primary
  # get primary card
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_customers_credit_cards_get_primary test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_customers_exist
  # check customer exist
  # @param phone 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_customers_exist test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_customers_me
  # customer show
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_customers_me test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_customers_point_history
  # get customer point history
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_customers_point_history test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_customers_pos_order_histories
  # get customer pos order history
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_customers_pos_order_histories test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_customers_store
  # get default store
  # @param brand_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_customers_store test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_customers_vip_barcode
  # customer vip barcode
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_customers_vip_barcode test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_event_pages
  # Event Page Index
  # @param brand_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_event_pages test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_event_pages_event_page_id
  # Event Page Show
  # @param event_page_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_event_pages_event_page_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_home_page
  # Home Page
  # @param brand_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_home_page test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_information
  # Information Index
  # @param brand_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [Integer] :offset 
  # @return [nil]
  describe 'get_v1_information test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_information_information_id
  # Information Show
  # @param information_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_information_information_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_maintain_orders
  # 維修保養單列表
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [Integer] :offset 
  # @return [nil]
  describe 'get_v1_maintain_orders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_maintain_orders_number
  # 維修保養單明細
  # @param number 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_maintain_orders_number test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_notifications
  # 推播列表
  # @param type 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset 
  # @option opts [Integer] :limit 
  # @return [nil]
  describe 'get_v1_notifications test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_notifications_id
  # 推播詳細資料
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_notifications_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_notifications_third_party_ping
  # Ping 檢查能不能打
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_notifications_third_party_ping test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_orders
  # list Orders
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [Integer] :offset 
  # @option opts [String] :status 
  # @return [nil]
  describe 'get_v1_orders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_orders_number
  # 取得特定訂單
  # @param number 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_orders_number test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_products_id
  # Product Show
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_products_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_products_query_stock
  # Query Stock
  # @param variant_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_products_query_stock test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_return_orders_id
  # 取得退貨單
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_return_orders_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_scrolling_texts
  # Scrolling Text Index
  # @param brand_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_scrolling_texts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_search
  # Search
  # @param keyword 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_series
  # Series Index
  # @param brand_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_series test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_series_series_id
  # Series Show
  # @param series_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_series_series_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_stores
  # Store Index
  # @param brand_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_stores test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_sub_collections
  # SubCollection Index
  # @param brand_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_sub_collections test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_sub_collections_id
  # SubCollection Show
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_sub_collections_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_sub_orders_id
  # 取得退貨子訂單
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_sub_orders_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_target_price_discounts
  # TargetPriceDiscount Index
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_target_price_discounts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_v1_top_banner
  # Show Top Banner
  # @param brand_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_v1_top_banner test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_carts
  # Update Cart
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_carts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_carts_add_favorites
  # Add to Favorite
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_carts_add_favorites test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customer_addresses
  # address create
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customer_addresses test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers
  # customer register
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_credit_cards
  # bind credit card
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_credit_cards test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_credit_cards_set_primary
  # set primary card
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_credit_cards_set_primary test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_login_with_otp
  # login with otp
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_login_with_otp test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_otp
  # customer request otp
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_otp test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_receive_notifications
  # 接收推播
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_receive_notifications test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_reset_password
  # reset password
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_reset_password test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_set_default_store
  # set default store
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_set_default_store test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_sso
  # SSO
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_sso test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_sso_bind
  # bind
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_sso_bind test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_sso_unbind
  # unbind
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_sso_unbind test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_sync_pos
  # sync customer with pos
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_sync_pos test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_update
  # customer update
  # @param [Hash] opts the optional parameters
  # @option opts [CustomersUpdateBody] :body 
  # @return [nil]
  describe 'post_v1_customers_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_update_password
  # update password
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_update_password test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_validate_otp
  # customer validate otp
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_validate_otp test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_customers_validate_password
  # validate password
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_customers_validate_password test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_maintain_orders
  # 創建維修保養單
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_maintain_orders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_maintain_orders_number_cancel
  # 取消維修保養單
  # @param number 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_maintain_orders_number_cancel test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_maintain_orders_number_quotation
  # 同意或取消報價
  # @param body 
  # @param number 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_maintain_orders_number_quotation test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_notification_bind
  # 推播註冊
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_notification_bind test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_notification_unbind
  # 解除推播註冊
  # @param [Hash] opts the optional parameters
  # @option opts [NotificationUnbindBody] :body 
  # @return [nil]
  describe 'post_v1_notification_unbind test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_notifications_read
  # 已讀單筆訂單
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_notifications_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_notifications_read_all
  # 已讀多筆訂單
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_notifications_read_all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_notifications_third_party
  # 第三方推播
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_notifications_third_party test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_notifications_third_party_customer_locale
  # [Deprecated] 取得語系
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_notifications_third_party_customer_locale test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_notifications_third_party_demo
  # 推播 Demo
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_notifications_third_party_demo test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_orders
  # 創建訂單
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_orders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_orders_number_cancel
  # 取消特定訂單
  # @param number 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_orders_number_cancel test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_orders_number_checkout
  # 結帳失敗後，做重新結帳的動作
  # @param body 
  # @param number 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_orders_number_checkout test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_products
  # Product Index
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_products test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_return_orders_id
  # 退貨表單送出
  # @param body 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_return_orders_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_v1_return_orders_pre_calculate_id
  # 取得返還金額、購物金
  # @param body 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_v1_return_orders_pre_calculate_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_v1_customer_addresses_id
  # address update
  # @param body 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'put_v1_customer_addresses_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
