=begin
#API title

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::CustomersReceiveNotificationsBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomersReceiveNotificationsBody' do
  before do
    # run before each test
    @instance = SwaggerClient::CustomersReceiveNotificationsBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomersReceiveNotificationsBody' do
    it 'should create an instance of CustomersReceiveNotificationsBody' do
      expect(@instance).to be_instance_of(SwaggerClient::CustomersReceiveNotificationsBody)
    end
  end
  describe 'test attribute "received"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "receive_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["email", "mobile"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.receive_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "notification_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["orders", "latest", "info"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.notification_type = value }.not_to raise_error
      # end
    end
  end

end
