=begin
#API title

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::CustomersCreditCardsBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomersCreditCardsBody' do
  before do
    # run before each test
    @instance = SwaggerClient::CustomersCreditCardsBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomersCreditCardsBody' do
    it 'should create an instance of CustomersCreditCardsBody' do
      expect(@instance).to be_instance_of(SwaggerClient::CustomersCreditCardsBody)
    end
  end
  describe 'test attribute "client_back_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
