=begin
#API title

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::NumberQuotationBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NumberQuotationBody' do
  before do
    # run before each test
    @instance = SwaggerClient::NumberQuotationBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NumberQuotationBody' do
    it 'should create an instance of NumberQuotationBody' do
      expect(@instance).to be_instance_of(SwaggerClient::NumberQuotationBody)
    end
  end
  describe 'test attribute "action"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["agree", "disagree"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.action = value }.not_to raise_error
      # end
    end
  end

end
