=begin
#API title

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::PreCalculateIdBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PreCalculateIdBody' do
  before do
    # run before each test
    @instance = SwaggerClient::PreCalculateIdBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PreCalculateIdBody' do
    it 'should create an instance of PreCalculateIdBody' do
      expect(@instance).to be_instance_of(SwaggerClient::PreCalculateIdBody)
    end
  end
  describe 'test attribute "items_variant_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "items_quantity"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
